#!/usr/bin/env node
/**
 * apply-patch.mjs — grok2api 한글 패치 적용기
 *
 * 대상(root) grok2api 체크아웃에 대해:
 *   1. frontend/src/shared/i18n/index.ts 를 완전히 재생성한다.
 *      - upstream 의 zh-CN/en 리소스를 그대로 보존
 *      - ko/*.json 사전을 적용한 ko 로케일 추가
 *      - 기본 언어를 한국어로 설정 (fallback: en → zh-CN)
 *   2. app-shell.tsx 언어 메뉴에 "한국어" 항목을 추가한다.
 *   3. index.html 의 html lang 을 ko 로 변경한다.
 *   4. assets/README.ko.md 를 대상 루트에 복사한다.
 *
 * 사전 검증(통합):
 *   - en 에 더 이상 없는 경로 → 건너뜀 (업스트림 변경 알림)
 *   - {{placeholder}} 집합이 en 과 다른 항목 → en 값 유지 (렌더링 보호)
 *
 * 사용법:
 *   node lib/apply-patch.mjs <targetRepoRoot>
 */
import { execSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { countLeaves, extractResources } from "./extract-i18n.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(process.argv[2] ?? process.cwd());
const koDir = join(here, "..", "ko");
const i18nPath = join(repoRoot, "frontend", "src", "shared", "i18n", "index.ts");

// ── 사전 로드: ko/<section>.json → { dot.path: 한국어 } ─────────────────────
function loadDictionary() {
  const dict = {};
  for (const file of readdirSync(koDir).filter((f) => f.endsWith(".json"))) {
    const section = file.replace(/\.json$/, "");
    const parsed = JSON.parse(readFileSync(join(koDir, file), "utf8"));
    if (parsed !== null && typeof parsed === "object") {
      (function walk(node, prefix) {
        for (const [key, value] of Object.entries(node)) {
          const p = prefix ? `${prefix}.${key}` : key;
          if (value !== null && typeof value === "object") walk(value, p);
          else dict[p] = value;
        }
      })(parsed, section);
    } else {
      dict[section] = parsed; // 최상위 문자열 섹션(appName 등)
    }
  }
  return dict;
}

function deepClone(value) {
  return value === null || typeof value !== "object" ? value : JSON.parse(JSON.stringify(value));
}

function resolvePath(root, path) {
  let node = root;
  for (const part of path.split(".")) {
    if (node === null || typeof node !== "object" || !(part in node)) return undefined;
    node = node[part];
  }
  return node;
}

function setAtPath(root, path, value) {
  const parts = path.split(".");
  let node = root;
  for (let i = 0; i < parts.length - 1; i += 1) {
    if (node[parts[i]] === null || typeof node[parts[i]] !== "object") node[parts[i]] = {};
    node = node[parts[i]];
  }
  node[parts[parts.length - 1]] = value;
}

const placeholders = (s) => (String(s).match(/{{[^}]+}}/g) ?? []).sort().join(",");

// ── 1. i18n index.ts 재생성 ───────────────────────────────────────────────
function generateI18nFile(resources, koTree, upstreamRef) {
  const payload = {
    "zh-CN": resources["zh-CN"],
    en: resources.en,
    ko: { translation: koTree },
  };
  const serialized = JSON.stringify(payload, null, 2);
  return `// AUTO-GENERATED by grok2api-kor patcher — do not edit manually.
// upstream: chenyme/grok2api${upstreamRef ? ` @ ${upstreamRef}` : ""}
// 재생성: bash patch.sh (grok2api-kor)
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = ${serialized} as const;

const SUPPORTED_LANGUAGES = ["ko", "en", "zh-CN"];

function readStoredLanguage(): string | null {
  if (typeof window === "undefined") return null;
  try {
    return window.localStorage.getItem("grok2api:language");
  } catch {
    return null;
  }
}

function storeLanguage(language: string): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem("grok2api:language", language);
  } catch {
    // Language changes still apply when browser storage is unavailable.
  }
}

const storedLanguage = readStoredLanguage();

const initialLanguage =
  storedLanguage !== null && SUPPORTED_LANGUAGES.indexOf(storedLanguage) !== -1
    ? storedLanguage
    : "ko";

void i18n.use(initReactI18next).init({
  resources,
  lng: initialLanguage,
  fallbackLng: ["en", "zh-CN"],
  interpolation: { escapeValue: false },
});

i18n.on("languageChanged", (language) => {
  storeLanguage(language);
  if (typeof document !== "undefined") document.documentElement.lang = language;
});

if (typeof document !== "undefined") document.documentElement.lang = i18n.language;

export { i18n };
`;
}

function applyI18nPatch(results) {
  const { resources } = extractResources(repoRoot);
  const dict = loadDictionary();
  const enFlatCount = countLeaves(resources.en.translation);

  const koTree = deepClone(resources.en.translation);
  let applied = 0;
  const stalePaths = [];
  const placeholderSkipped = [];
  for (const [path, value] of Object.entries(dict)) {
    const enValue = resolvePath(resources.en.translation, path);
    if (enValue === undefined || (enValue !== null && typeof enValue === "object")) {
      stalePaths.push(path);
      continue;
    }
    if (placeholders(enValue) !== placeholders(value)) {
      placeholderSkipped.push(path);
      continue; // en 값 유지 — 렌더링 파손 방지
    }
    setAtPath(koTree, path, value);
    applied += 1;
  }
  if (stalePaths.length > 0) {
    console.warn(
      `경고: upstream에서 사라져 건너뛴 경로 ${stalePaths.length}건 (사전 정리 대상):\n  ${stalePaths.slice(0, 20).join("\n  ")}${stalePaths.length > 20 ? "\n  ..." : ""}`,
    );
  }
  if (placeholderSkipped.length > 0) {
    console.warn(
      `경고: {{placeholder}}가 달라 en 값으로 대체한 항목 ${placeholderSkipped.length}건 (재번역 대상):\n  ${placeholderSkipped.slice(0, 20).join("\n  ")}${placeholderSkipped.length > 20 ? "\n  ..." : ""}`,
    );
  }
  const untranslated = enFlatCount - applied - stalePaths.length - placeholderSkipped.length;

  let upstreamRef = "";
  try {
    upstreamRef = execSync("git rev-parse --short HEAD", { cwd: repoRoot, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    // git 이 없는 환경에서는 스킵
  }

  const generated = generateI18nFile(resources, koTree, upstreamRef);
  writeFileSync(i18nPath, generated);

  // 자체 검증: 생성된 파일을 다시 평가해서 ko 리프 수가 en 과 동일한지 확인한다.
  const tmpRoot = mkdtempSync(join(tmpdir(), "g2ak-selftest-"));
  try {
    const tmpI18nDir = join(tmpRoot, "frontend", "src", "shared", "i18n");
    mkdirSync(tmpI18nDir, { recursive: true });
    copyFileSync(i18nPath, join(tmpI18nDir, "index.ts"));
    const re = extractResources(tmpRoot);
    const koLeaves = countLeaves(re.resources.ko?.translation ?? {});
    if (koLeaves !== enFlatCount) {
      throw new Error(`자체 검증 실패: ko 리프 ${koLeaves} != en 리프 ${enFlatCount}`);
    }
    results.push(
      `frontend/src/shared/i18n/index.ts — ko 로케일 ${koLeaves}항목 (번역 ${applied} · en 폴백 ${untranslated}) · 기본 언어 ko`,
    );
  } finally {
    rmSync(tmpRoot, { recursive: true, force: true });
  }
}

// ── 2. app-shell.tsx 언어 메뉴 ────────────────────────────────────────────
function applyShellPatch(results) {
  const shellPath = join(repoRoot, "frontend", "src", "app", "app-shell.tsx");
  let src = readFileSync(shellPath, "utf8");
  if (src.includes('changeLanguage("ko")')) {
    results.push("frontend/src/app/app-shell.tsx — 이미 한국어 메뉴가 있음 (스킵)");
    return;
  }
  const lines = src.split("\n");
  const idx = lines.findIndex((l) => l.includes('changeLanguage("zh-CN")'));
  if (idx === -1) {
    console.warn("경고: app-shell.tsx 에서 zh-CN 언어 메뉴를 찾지 못했습니다. 업스트림 UI 변경 가능성이 있습니다.");
    return;
  }
  const indent = lines[idx].match(/^\s*/)?.[0] ?? "              ";
  lines.splice(idx, 0, `${indent}<DropdownMenuItem onClick={() => void i18n.changeLanguage("ko")}>한국어</DropdownMenuItem>`);
  writeFileSync(shellPath, lines.join("\n"));
  results.push("frontend/src/app/app-shell.tsx — 언어 메뉴에 한국어 추가");
}

// ── 3. index.html lang ────────────────────────────────────────────────────
function applyHtmlPatch(results) {
  const htmlPath = join(repoRoot, "frontend", "index.html");
  let html = readFileSync(htmlPath, "utf8");
  if (html.includes('<html lang="ko">')) {
    results.push("frontend/index.html — 이미 lang=ko (스킵)");
    return;
  }
  const next = html.replace(/<html lang="zh-CN">/, '<html lang="ko">').replace(/<html lang="en">/, '<html lang="ko">');
  if (next === html) {
    console.warn("경고: index.html 에서 html lang 을 찾지 못했습니다.");
    return;
  }
  writeFileSync(htmlPath, next);
  results.push("frontend/index.html — html lang 을 ko 로 변경");
}

// ── 4. README.ko.md ───────────────────────────────────────────────────────
function applyReadmePatch(results) {
  const src = join(here, "..", "assets", "README.ko.md");
  const dst = join(repoRoot, "README.ko.md");
  if (!existsSync(src)) {
    console.warn("경고: assets/README.ko.md 가 없습니다.");
    return;
  }
  copyFileSync(src, dst);
  results.push("README.ko.md — 프로젝트 루트에 배치");
}

// ── 실행 ─────────────────────────────────────────────────────────────────
const results = [];
applyI18nPatch(results);
applyShellPatch(results);
applyHtmlPatch(results);
applyReadmePatch(results);
console.log(`한글 패치 적용 완료 (${repoRoot}):`);
for (const line of results) console.log(`  - ${line}`);
